# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('asocnumber_id', models.AutoField(primary_key=True, serialize=False)),
                ('asoc_name', models.CharField(blank=True, max_length=50, null=True)),
                ('asoc_stardate', models.DateTimeField(blank=True, null=True)),
                ('trans_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Association',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expensenumber_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_date', models.DateTimeField(blank=True, null=True)),
                ('asocnumber_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Association')),
            ],
            options={
                'db_table': 'Expense',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('student_status', models.BooleanField(default=False)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Member',
            },
        ),
        migrations.CreateModel(
            name='member_asoc',
            fields=[
                ('asocnmember_id', models.AutoField(primary_key=True, serialize=False)),
                ('join_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('asocnumber_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Association')),
                ('member_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'member_asoc',
            },
        ),
        migrations.CreateModel(
            name='member_expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asocnumber_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Association')),
                ('expensenumber_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Expense')),
                ('payment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'member_expense',
            },
        ),
    ]
