# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asoc_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'Association',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_no', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Association')),
            ],
            options={
                'db_table': 'Member',
            },
        ),
        migrations.CreateModel(
            name='AssociationSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Association Summary',
                'verbose_name_plural': 'Association Summary',
                'proxy': True,
            },
            bases=('member.association',),
        ),
        migrations.CreateModel(
            name='MemberSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Member Summary',
                'verbose_name_plural': 'Member Summary',
                'proxy': True,
            },
            bases=('member.member',),
        ),
    ]
