# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='administrator',
            table=None,
        ),
    ]
