# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
