# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoAdmin', '0002_auto_20170413_0316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={},
        ),
        migrations.AlterModelTable(
            name='administrator',
            table='Administrator',
        ),
    ]
